version: "3.9"

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: blockscout
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blockscout
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  smart-contract-verifier:
    image: ghcr.io/blockscout/smart-contract-verifier:latest
    restart: unless-stopped
    environment:
      - RUST_LOG=info
    ports:
      - "8050:8050"

  blockscout:
    image: ghcr.io/blockscout/blockscout:latest
    restart: unless-stopped
    depends_on:
      - db
      - redis
      - smart-contract-verifier
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # Core DB + Network settings
      DATABASE_URL: postgres://blockscout:password@db:5432/blockscout
      ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:8545/
      ETHEREUM_JSONRPC_TRACE_URL: http://host.docker.internal:8545/
      ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:8545/
      ETHEREUM_JSONRPC_VARIANT: geth
      NETWORK: Local Hardhat
      CHAIN_ID: "1337"
      COIN: ETH
      PORT: "4000"

      # Features and housekeeping
      SECRET_KEY_BASE: 0b7a9c2f6e2e4e0f9a3b1c7d8e6f4a2b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5
      SMART_CONTRACT_VERIFIER_URL: http://smart-contract-verifier:8050
      ECTO_USE_SSL: "false"
      DISABLE_WEBAPP: "false"
      DISABLE_WEBAPP__API_DOCS: "false"
      API_V2_ENABLED: "true"
      API_V2_WRITE_METHODS_ENABLED: "true"

      # Optional: speed up syncing for dev
      MIX_ENV: prod
      BLOCKSCOUT_LOG: info
      BLOCKSCOUT_HOST: localhost:8080
      BLOCKSCOUT_PROTOCOL: http
      INDEXER_DISABLE_INTERNAL_TRANSACTIONS: "false"
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: "true"
      INDEXER_DISABLE_CSV_EXPORTER: "true"

    ports:
      - "4000:4000"

  frontend:
    image: ghcr.io/blockscout/frontend:latest
    restart: unless-stopped
    environment:
      # Frontend will call API through the same-origin proxy on :8080
      NEXT_PUBLIC_API_HOST: localhost:8080
      NEXT_PUBLIC_API_PROTOCOL: http
      NEXT_PUBLIC_API_BASE_PATH: /node-api/proxy
      NEXT_PUBLIC_APP_HOST: localhost:8080
      NEXT_PUBLIC_APP_PROTOCOL: http
      NEXT_PUBLIC_NETWORK_NAME: Local Hardhat
      NEXT_PUBLIC_NETWORK_SHORT_NAME: Local Hardhat
      NEXT_PUBLIC_NETWORK_ID: 1337
      NEXT_PUBLIC_NETWORK_CURRENCY_NAME: Ether
      NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL: ETH
      NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS: 18
      NEXT_PUBLIC_HOMEPAGE_CHARTS: "['daily_txs']"
      NEXT_PUBLIC_IS_TESTNET: "true"
      NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: ws
      NEXT_PUBLIC_API_SPEC_URL: https://raw.githubusercontent.com/blockscout/blockscout-api-v2-swagger/main/swagger.yaml
    ports:
      - "3000:3000"

  proxy:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - frontend
      - blockscout
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data:
